Hospital_Appointment_System_MVC_Project/Controllers/AppointmentController.cs
using Hospital_Appointment_System_MVC_Project.Infrastructure.EntityTypeConfiguration.Repositories.Interface;
using Hospital_Appointment_System_MVC_Project.Infrastructure.Service;
using Hospital_Appointment_System_MVC_Project.Models.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace Hospital_Appointment_System_MVC_Project.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly IAppointmentService _appointmentService;
        public AppointmentController(IAppointmentService appointmentService)
        {
            _appointmentService = appointmentService;
        }   
        
        
        [HttpGet]
        public IActionResult Create()
        {
            AppointmentCreateDTO model = _appointmentService.GetPatientDoctor();


            return View(model);
        }

        [HttpPost]
        public IActionResult Create(AppointmentCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                _appointmentService.Create(model);
            
                return RedirectToAction("List");
            }
            else
            {
                return View(model);
            }
            
        }
        public IActionResult List()
        {
            return View(_appointmentService.Gets());
        }

        public IActionResult Delete(int id)
        {
            _appointmentService.Delete(id);
            return RedirectToAction("List");
        }

        public IActionResult Details(int id)
        {
            return View(_appointmentService.GetDetails(id));
        }
    }
}

Hospital_Appointment_System_MVC_Project/Controllers/DoctorController.cs
using Hospital_Appointment_System_MVC_Project.Infrastructure.EntityTypeConfiguration.Repositories.Interface;
using Hospital_Appointment_System_MVC_Project.Infrastructure.Service;
using Hospital_Appointment_System_MVC_Project.Models.DTOs;
using Hospital_Appointment_System_MVC_Project.Models.Entities;
using Hospital_Appointment_System_MVC_Project.Models.VMs;
using Microsoft.AspNetCore.Mvc;

namespace Hospital_Appointment_System_MVC_Project.Controllers
{
    public class DoctorController : Controller
    {
        private IDoctorService _doctorService;

        public DoctorController(IDoctorService doctorService)
        {
            this._doctorService = doctorService;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(DoctorCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                _doctorService.Create(model);
                return RedirectToAction("List");
            }
            else
            {
                return View(model);
            }

        }

        public IActionResult List()
        {

            return View(_doctorService.GetAll());
        }

        public IActionResult Details(int id)
        {

            return View(_doctorService.GetDetails(id));
        }

        public IActionResult Update(int id)
        {

            return View(_doctorService.Get(id));
        }
        [HttpPost]
        public IActionResult Update(DoctorUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                _doctorService.Update(model);
                return RedirectToAction("List");
            }
            else
            {
                return View(model);
            }
        }

        public IActionResult Delete(int id)
        {
            _doctorService.Delete(id);
            return RedirectToAction("List");
        }
    }
}

Hospital_Appointment_System_MVC_Project/Controllers/PatientController.cs
using Hospital_Appointment_System_MVC_Project.Infrastructure.EntityTypeConfiguration.Repositories.Interface;
using Hospital_Appointment_System_MVC_Project.Infrastructure.Service;
using Hospital_Appointment_System_MVC_Project.Models.DTOs;
using Hospital_Appointment_System_MVC_Project.Models.Entities;
using Hospital_Appointment_System_MVC_Project.Models.VMs;
using Microsoft.AspNetCore.Mvc;

namespace Hospital_Appointment_System_MVC_Project.Controllers
{
    public class PatientController : Controller
    {

        private IPatientService _patientService;

        public PatientController(IPatientService patientService)
        {
            this._patientService = patientService;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PatientCreateDTO model)
        {
            if (ModelState.IsValid)
            {               
                _patientService.Create(model);
                return RedirectToAction("List");
            }
            else
            {
                return View(model);
            }

        }

        public IActionResult List()
        {
            return View(_patientService.GetAll());
        }

        public IActionResult Details(int id)
        { 
            return View(_patientService.GetDetails(id));
        }

        public IActionResult Update(int id)
        {

            return View(_patientService.Get(id));
        }
        [HttpPost]
        public IActionResult Update(PatientUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                _patientService.Update(model);
                return RedirectToAction("List");
            }
            else
            {
                return View(model);
            }
        }

        public IActionResult Delete(int id)
        {
      
            _patientService.Delete(id);
            return RedirectToAction("List");
        }

    }
}

Hospital_Appointment_System_MVC_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hospital_Appointment_System_MVC_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hospital_Appointment_System_MVC_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hospital Appointment System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Create" asp-controller="Appointment">Add Appointment </a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="List" asp-controller="Appointment">Appointment List</a>
                        </li>
                         @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Details" asp-controller="Appointment">Appointment Details</a>
                        </li>*@
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Create" asp-controller="Doctor">Add Doctor</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="List" asp-controller="Doctor">Doctor List</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Details" asp-controller="Doctor">Details Doctor</a>
                        </li>*@
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Update" asp-controller="Doctor">Update Doctor</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Create" asp-controller="Patient">Create Patient</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="List" asp-controller="Patient">Patient List</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Update" asp-action="Patient">Patient Update</a>
                        </li>*@
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Details" asp-action="Patient">Add Appointment</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Hospital_Appointment_System_MVC_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>